/**
 * Produces the Phase 0.5 review package:
 *   - a full-dataset size estimate, measured (not guessed) by compacting the sample,
 *     gzipping it, and extrapolating to ~10k lemmas, plus the real size of the
 *     form -> lemma search index restricted to those lemmas
 *   - DATA_SOURCES.md in the brief section 4 format
 *   - out/07-review-records.md: ~20 generated records for the owner to read
 *
 * Run: node pipeline/spike/07-report.mjs
 */
import zlib from "node:zlib";
import path from "node:path";
import fs from "node:fs";
import { raw, out, writeJson, readJson, SPIKE_DIR, mb, kb } from "./lib/io.mjs";

const TARGET_LEMMAS = 10000;
const REPO = path.resolve(SPIKE_DIR, "../..");

const sample = readJson(out("06-sample-entries-with-examples.json"));
const conjugations = readJson(out("05-conjugations.json"));
const indexStats = readJson(out("03-index-stats.json"));
const formReport = readJson(out("04-form-lemma-report.json"));
const conjCoverage = readJson(out("05-conjugation-coverage.json"));
const exampleCoverage = readJson(out("06-example-coverage.json"));
const manifest = readJson(raw("_manifest.json"));
const { sources } = readJson(path.join(SPIKE_DIR, "sources.json"));

// ---- size estimate --------------------------------------------------------
/** The shape actually shipped to the phone: no debug fields, no per-entry form list. */
const compact = (e) => ({
  i: e.id,
  l: e.lemma,
  p: e.pos,
  ...(e.gender ? { g: e.gender } : {}),
  ...(e.conjugationId ? { c: e.conjugationId } : {}),
  ...(e.freqRank ? { r: e.freqRank } : {}),
  s: e.senses.map((s) => (s.regionLabels.length ? [s.gloss, s.regionLabels] : [s.gloss])),
  x: e.examples.map((x) => [x.es, x.en, x.sourceId, x.contributor]),
});

const compactEntries = sample.entries.map(compact);
const entriesJson = Buffer.from(JSON.stringify(compactEntries), "utf8");
const entriesGz = zlib.gzipSync(entriesJson, { level: 9 });
const perEntryRaw = entriesJson.length / sample.entries.length;
const perEntryGz = entriesGz.length / sample.entries.length;

// conjugation tables: measure one, extrapolate to the number of verbs in 10k lemmas
const conjJson = Buffer.from(JSON.stringify(conjugations), "utf8");
const conjGz = zlib.gzipSync(conjJson, { level: 9 });
const conjCount = Object.keys(conjugations).length || 1;
const perConjGz = conjGz.length / conjCount;

const ranked = readJson(raw("_lemma-ranks.json")).ranked;
const top = ranked.slice(0, TARGET_LEMMAS);
const verbShare = top.filter((r) => r.pos === "verb").length / top.length;

// real size of the search index restricted to the top lemmas
const wantedKeys = new Set(top.map((r) => `${r.lemma}|${r.pos}`));
const fullIndex = readJson(raw("_form-index.json"));
const trimmed = {};
for (const [form, hits] of Object.entries(fullIndex)) {
  const keep = hits.filter((h) => wantedKeys.has(h));
  if (keep.length) trimmed[form] = keep;
}
const indexJson = Buffer.from(JSON.stringify(trimmed), "utf8");
const indexGz = zlib.gzipSync(indexJson, { level: 9 });

const estVerbs = Math.round(TARGET_LEMMAS * verbShare);
const estEntriesGz = perEntryGz * TARGET_LEMMAS;
const estConjGz = perConjGz * estVerbs;
const estTotalGz = estEntriesGz + estConjGz + indexGz.length;

const size = {
  generatedAt: new Date().toISOString(),
  measuredOn: { sampleEntries: sample.entries.length, conjugationTables: conjCount },
  perEntryBytes: { rawJson: Math.round(perEntryRaw), gzipped: Math.round(perEntryGz) },
  projectedFor: TARGET_LEMMAS,
  projected: {
    entriesGzip: Math.round(estEntriesGz),
    conjugationsGzip: Math.round(estConjGz),
    searchIndexGzip: indexGz.length,
    searchIndexRaw: indexJson.length,
    totalGzip: Math.round(estTotalGz),
    totalGzipHuman: mb(estTotalGz),
  },
  estimatedVerbsInTop10k: estVerbs,
  distinctFormsInTrimmedIndex: Object.keys(trimmed).length,
  chunkingSketch: {
    note: "Section 11 requires a chunked, resumable, atomic download.",
    suggestedChunks: Math.max(1, Math.ceil(estTotalGz / (600 * 1024))),
    chunkTargetBytes: 600 * 1024,
  },
};
writeJson(out("07-size-estimate.json"), size);

// ---- DATA_SOURCES.md ------------------------------------------------------
const lines = [];
lines.push("# Data sources", "");
lines.push("Every dataset bundled with or used to build Mi cuaderno's reference layer, with the exact license");
lines.push("stated by the source at download time. Generated by `pipeline/spike/07-report.mjs` — do not edit by hand.", "");
lines.push(`Dataset version: **${sample.datasetVersion}**  ·  Generated: ${new Date().toISOString().slice(0, 10)}`, "");
lines.push("> **Licensing note:** the app's own code is licensed separately from this data. The Jehle");
lines.push("> conjugation database is **noncommercial** (CC BY-NC-SA 3.0); it must never be relicensed");
lines.push("> together with the app code, and it rules out any commercial use of this app.", "");

for (const s of sources) {
  const d = manifest.downloads[s.key] || {};
  lines.push(`## ${s.name}`, "");
  lines.push(`- **Source URL:** ${s.url}`);
  lines.push(`- **Landing page:** ${s.landingPage}`);
  lines.push(`- **Downloaded:** ${d.downloadedAt || "—"} (${d.size || "—"}, sha256 \`${(d.sha256 || "").slice(0, 16)}…\`)`);
  lines.push(`- **License:** ${s.license}`);
  lines.push(`- **License text as stated by the source:** "${s.licenseQuote}" — verified at ${s.licenseVerifiedAt}`);
  lines.push(`- **Required attribution:** ${s.attribution}`);
  if (s.upstream) lines.push(`- **Upstream:** ${s.upstream}`);
  lines.push(`- **Notes:** ${s.notes}`);
  lines.push("");
}

lines.push("## Transformations applied", "");
lines.push("| Step | Script | What it does |");
lines.push("|---|---|---|");
lines.push("| Download + provenance | `pipeline/spike/01-download.mjs` | Fetches each source; records size, sha256 and download timestamp |");
lines.push("| Index build | `pipeline/spike/03-build-index.mjs` | Builds the form→lemma index from `forms[]` and `form_of` records; assigns canonical IDs; merges records sharing word+pos+etymology |");
lines.push("| Frequency aggregation | `pipeline/spike/04-form-lemma.mjs` | Aggregates OpenSubtitles token counts into lemma ranks (citation-first ambiguity policy) |");
lines.push("| Entry build + conjugations | `pipeline/spike/05-build-sample.mjs` | Builds DictEntry records, sorts Mexico-labeled senses first, joins Jehle conjugations (ustedes-first, vosotros collapsed) |");
lines.push("| Examples | `pipeline/spike/06-join-examples.mjs` | Attaches ≤3 Tatoeba es↔en pairs, each with sentence ID, contributor, license and URL |");
lines.push("| Report | `pipeline/spike/07-report.mjs` | Produces this file, the size estimate and the review records |");
lines.push("");
fs.writeFileSync(path.join(REPO, "DATA_SOURCES.md"), lines.join("\n"), "utf8");

// ---- human-readable review records ---------------------------------------
const pick = (pred, n) => sample.entries.filter(pred).slice(0, n);
const mexico = pick((e) => e.senses.some((s) => s.regionLabels.some((l) => /^Mexico$/i.test(l))), 6);
const verbsWithConj = pick((e) => e.conjugationId, 4);
const nouns = pick((e) => e.pos === "noun" && e.gender, 4);
const adjectives = pick((e) => e.pos === "adj", 2);
const merged = pick((e) => e.mergedFromRecords > 1, 2);
const noConj = pick((e) => e.pos === "verb" && !e.conjugationId, 2);

const chosen = [];
const seen = new Set();
for (const e of [...verbsWithConj, ...mexico, ...nouns, ...adjectives, ...merged, ...noConj]) {
  if (!seen.has(e.id)) { seen.add(e.id); chosen.push(e); }
}

const md = [];
md.push("# Phase 0.5 — generated records for review", "");
md.push(`${chosen.length} records generated by the spike pipeline, chosen to cover the cases the brief calls out:`);
md.push("verbs with conjugations, Mexico-labeled senses, nouns with gender, adjectives, merged entries, and a verb Jehle lacks.", "");
md.push(`Dataset version: \`${sample.datasetVersion}\``, "");
md.push("---", "");

for (const e of chosen) {
  md.push(`### ${e.lemma}  *(${e.pos}${e.gender ? `, ${e.gender}` : ""})*`, "");
  md.push(`- **ID:** \`${e.id}\``);
  md.push(`- **Frequency rank:** ${e.freqRank ?? "—"}${e.mergedFromRecords > 1 ? `  ·  merged from ${e.mergedFromRecords} kaikki records` : ""}`);
  md.push(`- **Searchable forms:** ${e.searchForms.length}${e.searchForms.length ? ` (e.g. ${e.searchForms.slice(0, 8).join(", ")}${e.searchForms.length > 8 ? ", …" : ""})` : ""}`);
  md.push(`- **Conjugation:** ${e.conjugationId ? `\`${e.conjugationId}\`` : "_none in Jehle — must be generated programmatically_"}`);
  md.push("", "**Senses**", "");
  for (const s of e.senses.slice(0, 6)) {
    md.push(`  ${s.regionLabels.length ? `**[${s.regionLabels.join(", ")}]** ` : ""}${s.gloss}`);
  }
  if (e.senses.length > 6) md.push(`  _…and ${e.senses.length - 6} more_`);
  md.push("");
  if (e.examples.length) {
    md.push("**Examples**", "");
    for (const x of e.examples) {
      md.push(`  - ${x.es}`);
      md.push(`    ${x.en}`);
      md.push(`    <sub>${x.sourceId} · contributor ${x.contributor || "(none)"} · ${x.license} · ${x.sourceUrl}</sub>`);
    }
    md.push("");
  }
  if (e.conjugationId && conjugations[e.conjugationId]) {
    const pres = conjugations[e.conjugationId].tenses["Indicative/Present"];
    if (pres) {
      md.push("**Present indicative** (ustedes-first; vosotros collapsed)", "");
      md.push(`  yo ${pres.yo} · tú ${pres.tú} · él/ella/usted ${pres["él/ella/usted"]} · nosotros ${pres.nosotros} · **ustedes/ellos ${pres["ustedes/ellos"]}** · _(vosotros ${pres.vosotros.form})_`);
      md.push("");
    }
  }
  md.push("---", "");
}
fs.writeFileSync(out("07-review-records.md"), md.join("\n"), "utf8");

console.log(`Size estimate for ${TARGET_LEMMAS.toLocaleString()} lemmas (gzipped):`);
console.log(`  entries              ${kb(estEntriesGz)}`);
console.log(`  conjugations (~${estVerbs} verbs) ${kb(estConjGz)}`);
console.log(`  search index         ${kb(indexGz.length)}  (raw ${mb(indexJson.length)})`);
console.log(`  TOTAL                ${mb(estTotalGz)}  -> ~${size.chunkingSketch.suggestedChunks} chunks of 600 KB`);
console.log(`\nPer entry: ${Math.round(perEntryRaw)} B raw, ${Math.round(perEntryGz)} B gzipped`);
console.log(`\nWrote DATA_SOURCES.md, out/07-size-estimate.json, out/07-review-records.md (${chosen.length} records)`);
